version: '3.4'

services:
  mssql:
      image: "mcr.microsoft.com/mssql/server:2019-latest"
  rabbitmq:
      image: "rabbitmq:3-management"
  efood.catalog.webapi:
    image: ${DOCKER_REGISTRY-}efoodcatalogwebapi
    build:
      context: .
      dockerfile: src/Services/Catalog/eFood.Catalog.WebApi/Dockerfile

  efood.basket.webapi:
    image: ${DOCKER_REGISTRY-}efoodbasketwebapi
    build:
      context: .
      dockerfile: src/Services/Basket/eFood.Basket.WebApi/Dockerfile

