version: '3.4'

services:
  mssql:
    ports:
        - "1433:1433"         
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "2wsx2WSX"
        MSSQL_PID: "Developer"
  efood.catalog.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    ports:
      - "5001:80"
